Challenge/Controllers/EnderecoController.cs
using Microsoft.AspNetCore.Mvc;
using Challenge.Models;
using Challenge.Repositories.Enderecos;
using Challenge.ViewModels;
using Challenge.Repositories.Usuarios;

namespace Challenge.Controllers
{
    public class EnderecoController : Controller
    {
        private readonly IEnderecoRepository _enderecoRepository;
        private readonly IUsuarioRepository _usuarioRepository;

        public EnderecoController(IEnderecoRepository enderecoRepository, IUsuarioRepository usuarioRepository)
        {
            _enderecoRepository = enderecoRepository;
            _usuarioRepository = usuarioRepository;
        }

        public IActionResult Index()
        {
            List<EnderecoModel> endereco = _enderecoRepository.BuscarTodos();
            return View(endereco);
        }

        public IActionResult Criar() 
        {
            var viewModel = new EnderecoViewModel
            {
                Endereco = new EnderecoModel(),
                Usuarios = _usuarioRepository.BuscarTodos()
            };
            return View(viewModel);
        }

        public IActionResult Apagar(int id)
        {
            EnderecoModel endereco = _enderecoRepository.ListarPorId(id);
            return View(endereco);
        }


        [HttpPost]
        public IActionResult Criar(EnderecoViewModel viewModel)
        {
  
            
            _enderecoRepository.Adicionar(viewModel.Endereco);
            return RedirectToAction("Index");
        }
        public IActionResult Editar(int id)
        {
            var endereco = _enderecoRepository.ListarPorId(id);
            var viewModel = new EnderecoViewModel
            {
                Endereco = endereco,
                Usuarios = _usuarioRepository.BuscarTodos()
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Atualizar(EnderecoViewModel viewModel)
        {
           
            var endereco = _enderecoRepository.ListarPorId(viewModel.Endereco.Id);

           

            endereco.Cep = viewModel.Endereco.Cep;
            endereco.Logradouro = viewModel.Endereco.Logradouro;
            endereco.Numero = viewModel.Endereco.Numero;
            endereco.Complemento = viewModel.Endereco.Complemento;
            endereco.UsuarioId = viewModel.Endereco.UsuarioId;

            _enderecoRepository.Atualizar(endereco);
            return RedirectToAction("Index");
        }



        public IActionResult DeletarEndereco(int id)
        {
            _enderecoRepository.Apagar(id);
            return RedirectToAction("Index");
        }
    }
}

Challenge/Controllers/PreferenciaViagemController.cs
using Microsoft.AspNetCore.Mvc;
using Challenge.Models;
using Challenge.Repositories.PreferenciaViagem;
using Challenge.ViewModels;
using Challenge.Repositories.Usuarios;

namespace Challenge.Controllers
{
    public class PreferenciaViagemController : Controller
    {
        private readonly IPreferenciaViagemRepository _preferenciaViagemRepository;
        private readonly IUsuarioRepository _usuarioRepository;

        public PreferenciaViagemController(IPreferenciaViagemRepository preferenciaViagemRepository, IUsuarioRepository usuarioRepository)
        {
            _preferenciaViagemRepository = preferenciaViagemRepository;
            _usuarioRepository = usuarioRepository;
        }

        public IActionResult Index()
        {
            List<PreferenciaViagemModel> preferencia = _preferenciaViagemRepository.BuscarTodos();
            return View(preferencia);
        }

        public IActionResult Criar() 
        {
            var viewModel = new PreferenciaViagemViewModel
            {
                PreferenciaViagem = new PreferenciaViagemModel(),
                Usuarios = _usuarioRepository.BuscarTodos()
            };
            return View(viewModel);
        }

        public IActionResult Apagar(int id)
        {
            PreferenciaViagemModel preferencia = _preferenciaViagemRepository.ListarPorId(id);
            return View(preferencia);
        }


        [HttpPost]
        public IActionResult Criar(PreferenciaViagemViewModel viewModel)
        {
  
            
            _preferenciaViagemRepository.Adicionar(viewModel.PreferenciaViagem);
            return RedirectToAction("Index");
        }
        public IActionResult Editar(int id)
        {
            var preferencia = _preferenciaViagemRepository.ListarPorId(id);
            var viewModel = new PreferenciaViagemViewModel
            {
                PreferenciaViagem = preferencia,
                Usuarios = _usuarioRepository.BuscarTodos()
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Atualizar(PreferenciaViagemViewModel viewModel)
        {
           
            var preferencia = _preferenciaViagemRepository.ListarPorId(viewModel.PreferenciaViagem.Id);

           

            // Atualizar as propriedades da preferência de viagem com os valores do formulário
            preferencia.TipoCulinaria = viewModel.PreferenciaViagem.TipoCulinaria;
            preferencia.RestricoesAlimentares = viewModel.PreferenciaViagem.RestricoesAlimentares;
            preferencia.TipoTransporte = viewModel.PreferenciaViagem.TipoTransporte;
            preferencia.TipoHospedagem = viewModel.PreferenciaViagem.TipoHospedagem;
            preferencia.ViajaSozinho = viewModel.PreferenciaViagem.ViajaSozinho;
            preferencia.UsuarioId = viewModel.PreferenciaViagem.UsuarioId;

            _preferenciaViagemRepository.Atualizar(preferencia);
            return RedirectToAction("Index");
        }



        public IActionResult DeletarPreferencia(int id)
        {
            _preferenciaViagemRepository.Apagar(id);
            return RedirectToAction("Index");
        }
    }
}

Challenge/Controllers/UsuarioController.cs
using Microsoft.AspNetCore.Mvc;
using Challenge.Models;
using Challenge.Repositories.Usuarios;
using Challenge.Data;

namespace Challenge.Controllers
{
    public class UsuarioController : Controller
    {
        private readonly IUsuarioRepository _usuarioRepository;

        public UsuarioController(IUsuarioRepository usuarioRepository)
        {
            _usuarioRepository = usuarioRepository;
        }

        
        public IActionResult Index()
        {
            List<UsuarioModel> user = _usuarioRepository.BuscarTodos();
            return View(user);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
           UsuarioModel user =  _usuarioRepository.ListarPorId(id);
            return View(user);
        }

        public IActionResult Apagar(int id)
        {
            UsuarioModel usuario = _usuarioRepository.ListarPorId(id);
            return View(usuario);
        }

       public IActionResult DeletarUsuario(int id)
        {
            _usuarioRepository.Apagar(id);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public IActionResult Criar(UsuarioModel user)
        {
            _usuarioRepository.Adicionar(user);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Alterar(UsuarioModel user)
        {
            _usuarioRepository.Atualizar(user);
            return RedirectToAction("Index");
        }
    } 
}

Challenge/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TechPeach</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Challenge.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TechPeach</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PreferenciaViagem" asp-action="Index">Preferencia de Viagem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Endereco" asp-action="Index">Enderecos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Challenge - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>